name: Build and Test Java

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: adopt

    - name: Install Maven dependencies
      run: mvn -s settings.xml dependency:resolve 

    - name: Build with Maven
      run: mvn -s settings.xml clean install  

    - name: Test
      run: mvn -s settings.xml test  
