name: Build and Test Java

on:
  push:
    branches:
      - main  # Replace 'main' with your main branch name
  pull_request:
    branches:
      - main  # Replace 'main' with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # You can specify the Java version you need here

    - name: Install Maven dependencies
      run: mvn dependency:resolve  # Resolve and install project dependencies

    - name: Build with Maven
      run: mvn clean install  # This command builds the project

    - name: Test
      run: mvn test  # This command runs the project tests
